name: fyp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get:
  responsive_sizer:
  flutter_launcher_icons:
  firebase_core: ^3.13.0
  url_launcher: ^6.3.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  fluttertoast: ^8.2.12
  file_picker: ^10.1.2
  audioplayers: ^6.4.0
  provider:
  flutter_easyloading:


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf






flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/main_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/main_logo.png"
