// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzs9TKXYVi8d6bCd1ZiwqWfAFg9IDp17k',
    appId: '1:125591212451:web:bccfc4da7026db8a99ca16',
    messagingSenderId: '125591212451',
    projectId: 'fypp-bb5ef',
    authDomain: 'fypp-bb5ef.firebaseapp.com',
    storageBucket: 'fypp-bb5ef.firebasestorage.app',
    measurementId: 'G-LR8T67W9KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRvn6FTOx-T-28jgKrddzCXI8UEQep644',
    appId: '1:125591212451:android:87217d0a17f60cd099ca16',
    messagingSenderId: '125591212451',
    projectId: 'fypp-bb5ef',
    storageBucket: 'fypp-bb5ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-xiggCmAw1LdNnaKg7xMZlYh50y5ey_A',
    appId: '1:125591212451:ios:c875d5e71ee5c7d399ca16',
    messagingSenderId: '125591212451',
    projectId: 'fypp-bb5ef',
    storageBucket: 'fypp-bb5ef.firebasestorage.app',
    iosBundleId: 'com.fyp.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-xiggCmAw1LdNnaKg7xMZlYh50y5ey_A',
    appId: '1:125591212451:ios:c875d5e71ee5c7d399ca16',
    messagingSenderId: '125591212451',
    projectId: 'fypp-bb5ef',
    storageBucket: 'fypp-bb5ef.firebasestorage.app',
    iosBundleId: 'com.fyp.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzs9TKXYVi8d6bCd1ZiwqWfAFg9IDp17k',
    appId: '1:125591212451:web:db8852ce6f18884399ca16',
    messagingSenderId: '125591212451',
    projectId: 'fypp-bb5ef',
    authDomain: 'fypp-bb5ef.firebaseapp.com',
    storageBucket: 'fypp-bb5ef.firebasestorage.app',
    measurementId: 'G-FZMY0CMBJP',
  );
}
